---
id: rubykaigi2023LT
base_name: bingo
tags: []
presentation_date: 
presentation_start_time: 
presentation_end_time: 
version: 1.0.0
licenses: []
slideshare_id: 
speaker_deck_id: 
vimeo_id: 
youtube_id: 
width: 800
height: 600
author:
  markup_language: :markdown
  name: Shugo Maeda
  email: 
  rubygems_user: shugo
  slideshare_user: 
  speaker_deck_user: 
